# Generated by Django 5.2.8 on 2026-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='ad_guid',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='role',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
