# Generated by Django 5.2.8 on 2026-02-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_erpuser_ad_guid_erpuser_is_active_erpuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='ERPGroup',
        ),
    ]
