# Generated by Django 5.2.8 on 2026-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_erpuser_group_delete_erpgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
