# Generated by Django 5.2.8 on 2026-02-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_erpuser_email_erpuser_extension_erpuser_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpuser',
            name='role',
        ),
    ]
