# Generated by Django 5.2.8 on 2026-02-05 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_erpuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ticket_type', models.CharField(choices=[('requisicao', 'Requisição'), ('melhoria', 'Melhoria'), ('incidente', 'Incidente'), ('programado', 'Programado')], max_length=20)),
                ('urgency', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado')], default='pendente', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='core.erpuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
