# Generated by Django 5.2.8 on 2026-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_tickets', to='core.erpuser'),
        ),
    ]
