# Generated by Django 5.2.8 on 2026-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(
                choices=[
                    ('nao_classificado', 'Não classificado'),
                    ('requisicao', 'Requisição'),
                    ('melhoria', 'Melhoria'),
                    ('incidente', 'Incidente'),
                    ('programado', 'Programado'),
                ],
                default='nao_classificado',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(
                choices=[
                    ('nao_classificado', 'Não classificado'),
                    ('baixa', 'Baixa'),
                    ('normal', 'Normal'),
                    ('media', 'Média'),
                    ('alta', 'Alta'),
                    ('urgente', 'Urgente'),
                ],
                default='nao_classificado',
                max_length=20,
            ),
        ),
    ]
