# Generated by Django 5.2.8 on 2026-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ticket_ticket_type_alter_ticket_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(
                choices=[
                    ('nao_classificado', 'Não classificado'),
                    ('programada', 'Programada'),
                    ('baixa', 'Baixa'),
                    ('media', 'Média'),
                    ('alta', 'Alta'),
                ],
                default='nao_classificado',
                max_length=20,
            ),
        ),
    ]
