# Generated by Django 5.2.8 on 2026-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ticket_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ticket', models.TextField(default='Novo chamado #{id}: {title} | {description}')),
                ('status_update', models.TextField(default='Chamado #{id} atualizado: {status} | {responsavel}')),
                ('new_message', models.TextField(default='Nova mensagem no chamado #{id}: {message}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
