# Generated by Django 5.2.8 on 2026-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whatsapptemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ticket_subject', models.CharField(default='[Chamado #{id}] Novo chamado', max_length=200)),
                ('new_ticket_body', models.TextField(default='Novo chamado #{id}: {title}\n{description}')),
                ('status_update_subject', models.CharField(default='[Chamado #{id}] Status atualizado', max_length=200)),
                ('status_update_body', models.TextField(default='Status atual: {status}\nResponsável: {responsavel}')),
                ('new_message_subject', models.CharField(default='[Chamado #{id}] Nova mensagem', max_length=200)),
                ('new_message_body', models.TextField(default='Nova mensagem: {message}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
