# Generated by Django 5.2.8 on 2026-02-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ticket_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_group_on_new_ticket', models.BooleanField(default=False)),
                ('send_group_on_assignment', models.BooleanField(default=True)),
                ('send_group_on_status', models.BooleanField(default=False)),
                ('send_group_on_message', models.BooleanField(default=False)),
                ('send_individual_on_new_ticket', models.BooleanField(default=False)),
                ('send_individual_on_assignment', models.BooleanField(default=True)),
                ('send_individual_on_status', models.BooleanField(default=True)),
                ('send_individual_on_message', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_optout', to='core.erpuser')),
            ],
        ),
    ]
