# Generated by Django 5.2.8 on 2026-02-06 16:10

from django.db import migrations, models


def copy_status_flags(apps, schema_editor):
    Settings = apps.get_model('core', 'WhatsAppNotificationSettings')
    for row in Settings.objects.all():
        old_group = getattr(row, 'send_group_on_status', False)
        old_individual = getattr(row, 'send_individual_on_status', True)
        row.send_group_on_status_pending = old_group
        row.send_group_on_status_in_progress = old_group
        row.send_group_on_status_closed = old_group
        row.send_individual_on_status_pending = old_individual
        row.send_individual_on_status_in_progress = old_individual
        row.send_individual_on_status_closed = old_individual
        row.save(update_fields=[
            'send_group_on_status_pending',
            'send_group_on_status_in_progress',
            'send_group_on_status_closed',
            'send_individual_on_status_pending',
            'send_individual_on_status_in_progress',
            'send_individual_on_status_closed',
        ])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_whatsappnotificationsettings_whatsappoptout'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_status_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_status_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_status_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_status_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_status_in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_status_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(copy_status_flags, noop_reverse),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_status',
        ),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_status',
        ),
    ]
