# Generated by Django 5.2.8 on 2026-02-06 16:40

from django.db import migrations, models


def copy_assignment_and_message_flags(apps, schema_editor):
    Settings = apps.get_model('core', 'WhatsAppNotificationSettings')
    for row in Settings.objects.all():
        old_assignment_group = getattr(row, 'send_group_on_assignment', True)
        old_assignment_individual = getattr(row, 'send_individual_on_assignment', True)
        old_message_group = getattr(row, 'send_group_on_message', False)
        old_message_individual = getattr(row, 'send_individual_on_message', True)

        row.send_group_on_assignment_new = old_assignment_group
        row.send_group_on_assignment_changed = old_assignment_group
        row.send_individual_on_assignment_new = old_assignment_individual
        row.send_individual_on_assignment_changed = old_assignment_individual

        row.send_group_on_message_internal = old_message_group
        row.send_group_on_message_user = old_message_group
        row.send_individual_on_message_internal = old_message_individual
        row.send_individual_on_message_user = old_message_individual

        row.save(update_fields=[
            'send_group_on_assignment_new',
            'send_group_on_assignment_changed',
            'send_individual_on_assignment_new',
            'send_individual_on_assignment_changed',
            'send_group_on_message_internal',
            'send_group_on_message_user',
            'send_individual_on_message_internal',
            'send_individual_on_message_user',
        ])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_whatsappnotificationsettings_split_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_assignment_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_assignment_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_message_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_message_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_assignment_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_assignment_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_message_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_message_user',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(copy_assignment_and_message_flags, noop_reverse),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_assignment',
        ),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_assignment',
        ),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_group_on_message',
        ),
        migrations.RemoveField(
            model_name='whatsappnotificationsettings',
            name='send_individual_on_message',
        ),
    ]
