# Generated by Django 5.2.8 on 2026-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_whatsappnotificationsettings_split_assignment_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('equipment', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('serial', models.CharField(blank=True, default='', max_length=120)),
                ('memory', models.CharField(blank=True, default='', max_length=60)),
                ('processor', models.CharField(blank=True, default='', max_length=120)),
                ('generation', models.CharField(blank=True, default='', max_length=60)),
                ('hd', models.CharField(blank=True, default='', max_length=120)),
                ('mod_hd', models.CharField(blank=True, default='', max_length=120)),
                ('windows', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
