# Generated by Django 5.2.8 on 2026-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_accessfolder_accessgroup_accessmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroup',
            name='access_level',
            field=models.CharField(choices=[('leitura', 'Leitura'), ('leitura_escrita', 'Leitura e escrita')], default='leitura', max_length=20),
        ),
    ]
