# Generated by Django 5.2.8 on 2026-02-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('received', 'Recebido')], default='pending_approval', max_length=30),
        ),
        migrations.CreateModel(
            name='RequisitionQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='requisitions/quotes/')),
                ('link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.requisition')),
            ],
        ),
    ]
