# Generated by Django 5.2.8 on 2026-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_requisition_status_requisitionquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
