# Generated by Django 5.2.8 on 2026-02-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_requisition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subquotes', to='core.requisitionquote'),
        ),
    ]
