# Generated by Django 5.2.8 on 2026-02-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_requisitionquote_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
