# Generated by Django 5.2.8 on 2026-02-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_requisitionquote_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
