# Generated by Django 5.2.8 on 2026-02-10 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_requisitionquote_is_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('pendente', 'Pendente'), ('programado', 'Programado'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado')], default='novo', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Criado'), ('status_changed', 'Status alterado'), ('assigned', 'Atribuído'), ('unassigned', 'Desatribuído'), ('reopened', 'Reaberto')], default='status_changed', max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_ti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_timeline_events', to='core.erpuser')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.ticket')),
            ],
        ),
    ]
