# Generated by Django 5.2.8 on 2026-02-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_migrate_pending_to_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_cycle_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_failure_type',
            field=models.CharField(blank=True, choices=[('ns', 'N/S'), ('equipamento', 'Equipamento'), ('software', 'Software')], default='', max_length=20),
        ),
    ]
