# Generated by Django 5.2.8 on 2026-02-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ticket_current_cycle_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('failure_type', models.CharField(choices=[('ns', 'N/S'), ('equipamento', 'Equipamento'), ('software', 'Software')], default='ns', max_length=20)),
                ('action_text', models.TextField(blank=True, default='')),
                ('priority_label', models.CharField(blank=True, default='', max_length=60)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('exported_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_work_logs', to='core.erpuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.ticket')),
            ],
        ),
    ]
