# Generated by Django 5.2.8 on 2026-02-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ticketworklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_inventory_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SoftwareInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('software_name', models.CharField(max_length=250)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('install_date', models.CharField(blank=True, default='', max_length=40)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_items', to='core.equipment')),
            ],
        ),
    ]
