# Generated by Django 5.2.8 on 2026-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_equipment_hostname_equipment_inventory_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
