# Generated by Django 5.2.8 on 2026-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_requisitionquote_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='historical_attendants',
            field=models.ManyToManyField(blank=True, related_name='handled_tickets', to='core.erpuser'),
        ),
    ]
