# Generated by Django 5.2.8 on 2026-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_ticket_historical_attendants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_failure_type',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('equipamento', 'Equipamento'), ('software', 'Software'), ('humana', 'Falha humana')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketworklog',
            name='failure_type',
            field=models.CharField(choices=[('na', 'N/A'), ('equipamento', 'Equipamento'), ('software', 'Software'), ('humana', 'Falha humana')], default='na', max_length=20),
        ),
    ]
