# Generated by Django 5.2.8 on 2026-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_dica'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tag_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
