# Generated by Django 5.2.8 on 2026-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_equipment_tag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='is_email_user',
            field=models.BooleanField(default=False),
        ),
    ]
