# Generated by Django 5.2.8 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_erpuser_is_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
