# Generated by Django 5.2.8 on 2026-02-19 16:47

import django.db.models.deletion
from django.db import migrations, models


def _split_email_tokens(raw_email: str) -> list[str]:
    raw = (raw_email or '').strip()
    if not raw:
        return []
    tokens = []
    for chunk in raw.replace(',', ';').split(';'):
        token = chunk.strip()
        if token and '@' in token:
            tokens.append(token)
    return tokens


def migrate_secondary_emails(apps, schema_editor):
    ERPUser = apps.get_model('core', 'ERPUser')
    EmailAlias = apps.get_model('core', 'EmailAlias')

    for user in ERPUser.objects.all().iterator():
        tokens = _split_email_tokens(user.email)
        if not tokens:
            continue
        primary = tokens[0]
        if user.email != primary:
            user.email = primary
            user.save(update_fields=['email'])
        for alias_email in tokens[1:]:
            EmailAlias.objects.get_or_create(user=user, email=alias_email)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_erpuser_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to='core.erpuser')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.RunPython(migrate_secondary_emails, migrations.RunPython.noop),
    ]
