# Generated by Django 5.2.8 on 2026-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_emailalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='email_last_sign_in',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='email_usage',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
