# Generated by Django 5.2.8 on 2026-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_erpuser_email_last_sign_in_erpuser_email_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aliases', models.TextField(blank=True, default='')),
                ('email_usage', models.CharField(blank=True, default='', max_length=80)),
                ('email_last_sign_in', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='json', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'email'],
            },
        ),
    ]
