# Generated by Django 5.2.8 on 2026-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_emailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='is_hidden_from_users',
            field=models.BooleanField(default=False),
        ),
    ]
