# Generated by Django 5.2.8 on 2026-02-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_mark_active_users_email_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttendantCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_cycles', to='core.erpuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_cycles', to='core.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'attendant')},
            },
        ),
    ]
