# Generated by Django 5.2.8 on 2026-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_ticketattendantcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dica',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='dicas/'),
        ),
    ]
