# Generated by Django 5.2.8 on 2026-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_dica_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='alimentacao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='equipment',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
