# Generated by Django 5.2.8 on 2026-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_equipment_alimentacao_equipment_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='baseboard_serial',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bios_serial',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bios_uuid',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hostname_aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mac_addresses',
            field=models.TextField(blank=True, default=''),
        ),
    ]
