# Generated by Django 5.2.8 on 2026-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_equipment_baseboard_serial_equipment_bios_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='needs_reconciliation',
            field=models.BooleanField(default=False),
        ),
    ]
