# Generated by Django 5.2.8 on 2026-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
