# Generated by Django 5.2.8 on 2026-02-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_requisitionquote_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionquote',
            name='payment_terms',
        ),
    ]
