# Generated by Django 5.2.8 on 2026-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_requisitionquote_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requisitions/quotes/files/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('pendente', 'Pendente'), ('programado', 'Programado'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='novo', max_length=20),
        ),
    ]
