# Generated by Django 5.2.8 on 2026-02-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_requisitionquote_attachment_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionQuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requisitions/quotes/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.requisitionquote')),
            ],
        ),
    ]
