# Generated by Django 5.2.8 on 2026-02-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_requisitionquoteattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionquote',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='RequisitionQuoteAttachment',
        ),
    ]
