# Generated by Django 5.2.11 on 2026-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
