# Generated by Django 5.2.11 on 2026-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_protocolo_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisition',
            name='partially_received_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('partially_received', 'Entregue parcial'), ('rejected', 'Reprovado'), ('received', 'Recebido')], default='pending_approval', max_length=30),
        ),
    ]
