# Generated by Django 5.2.11 on 2026-03-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_requisition_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquote',
            name='payment_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisitionquote',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='RequisitionQuoteDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_entries', to='core.requisitionquote')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
