# Generated by Django 5.2.11 on 2026-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_requisitionquote_payment_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionquotediscount',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionquotediscount',
            name='previous_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requisitionquotediscount',
            name='updated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
