# Generated by Django 5.2.11 on 2026-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_requisitionquotediscount_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='antivirus_names',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defender_realtime_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defender_service_running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fw_domain_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fw_private_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fw_public_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_security_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
