# Generated by Django 5.2.11 on 2026-03-20 00:00

from django.db import migrations, models


def copy_responsibility_assignee_to_many(apps, schema_editor):
    Responsibility = apps.get_model('core', 'Responsibility')
    for item in Responsibility.objects.exclude(assigned_to__isnull=True).only('id', 'assigned_to_id'):
        if item.assigned_to_id:
            item.assignees.add(item.assigned_to_id)


def copy_many_assignees_to_single_assignee(apps, schema_editor):
    Responsibility = apps.get_model('core', 'Responsibility')
    for item in Responsibility.objects.all():
        first_assignee_id = item.assignees.order_by('id').values_list('id', flat=True).first()
        Responsibility.objects.filter(id=item.id).update(assigned_to_id=first_assignee_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_responsibilities', to='core.erpuser'),
        ),
        migrations.RunPython(
            copy_responsibility_assignee_to_many,
            copy_many_assignees_to_single_assignee,
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='assigned_to',
        ),
    ]
