# Generated by Django 5.2.11 on 2026-03-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_responsibility_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='description',
        ),
    ]
