# Generated by Django 5.2.11 on 2026-04-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_planoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='auto_pause_play_tickets_at_end_of_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattendantcycle',
            name='manual_resolution_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattendantcycle',
            name='manual_resolution_pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
