# Generated by Django 5.2.11 on 2026-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_erpuser_auto_pause_play_tickets_at_end_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketworklog',
            name='manual_resolution_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketworklog',
            name='requires_manual_resolution',
            field=models.BooleanField(default=False),
        ),
    ]
