# Generated by Codex on 2026-04-09

from django.db import migrations


def rebuild_legacy_pendencia_table(apps, schema_editor):
    Pendencia = apps.get_model('core', 'Pendencia')
    connection = schema_editor.connection
    table_name = Pendencia._meta.db_table

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with connection.cursor() as cursor:
        current_columns = [
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        ]

    expected_columns = [field.column for field in Pendencia._meta.local_concrete_fields]
    if set(current_columns) == set(expected_columns):
        return

    quote_name = schema_editor.quote_name
    backup_table_name = f'{table_name}_legacy_0079'

    if backup_table_name in existing_tables:
        schema_editor.execute(f'DROP TABLE {quote_name(backup_table_name)}')

    schema_editor.execute(
        f'ALTER TABLE {quote_name(table_name)} RENAME TO {quote_name(backup_table_name)}'
    )
    schema_editor.create_model(Pendencia)

    common_columns = [column for column in expected_columns if column in current_columns]
    if common_columns:
        quoted_columns = ', '.join(quote_name(column) for column in common_columns)
        schema_editor.execute(
            f'INSERT INTO {quote_name(table_name)} ({quoted_columns}) '
            f'SELECT {quoted_columns} FROM {quote_name(backup_table_name)}'
        )

    schema_editor.execute(f'DROP TABLE {quote_name(backup_table_name)}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_ticketworklog_manual_resolution_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(rebuild_legacy_pendencia_table, migrations.RunPython.noop),
    ]
