# Generated by Django 5.2.11 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_rebuild_legacy_passwordvaultitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencia',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='pendencia',
            options={'ordering': ['is_done', '-is_urgent', '-created_at', '-id']},
        ),
    ]
