from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    ChamadosView,
    CustomLoginView,
    DashboardView,
    AcessosView,
    EquipamentosView,
    RequisicoesView,
    RelatoriosView,
    UsersListView,
    move_ticket,
    ticket_detail,
    ticket_reclassify,
    ticket_message,
    ticket_update,
    email_templates_update,
    whatsapp_group_lookup,
    whatsapp_templates_update,
    whatsapp_settings_update,
    ticket_reopen,
    ws_tickets_ping,
)

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('usuarios/', UsersListView.as_view(), name='usuarios'),
    path('acessos/', AcessosView.as_view(), name='acessos'),
    path('equipamentos/', EquipamentosView.as_view(), name='equipamentos'),
    path('requisicoes/', RequisicoesView.as_view(), name='requisicoes'),
    path('relatorios/', RelatoriosView.as_view(), name='relatorios'),
    path('chamados/', ChamadosView.as_view(), name='chamados'),
    path('chamados/mover/', move_ticket, name='chamados_mover'),
    path('chamados/detalhe/<int:ticket_id>/', ticket_detail, name='chamados_detalhe'),
    path('chamados/reclassificar/', ticket_reclassify, name='chamados_reclassificar'),
    path('chamados/mensagem/', ticket_message, name='chamados_mensagem'),
    path('chamados/atualizar/', ticket_update, name='chamados_atualizar'),
    path('chamados/email-templates/', email_templates_update, name='chamados_email_templates'),
    path('chamados/whatsapp-templates/', whatsapp_templates_update, name='chamados_whatsapp_templates'),
    path('chamados/whatsapp-group-lookup/', whatsapp_group_lookup, name='chamados_whatsapp_group_lookup'),
    path('chamados/whatsapp-settings/', whatsapp_settings_update, name='chamados_whatsapp_settings'),
    path('chamados/reabrir/', ticket_reopen, name='chamados_reabrir'),
    path('ws/tickets/', ws_tickets_ping, name='ws_tickets_ping'),
    path('', DashboardView.as_view(), name='dashboard'),
]
