from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    ChamadosView,
    CustomLoginView,
    DashboardView,
    AtribuicoesView,
    AtribuicoesReportView,
    PendenciasView,
    AcessosView,
    EquipamentosView,
    SoftwaresView,
    InsumosView,
    ProtocolosView,
    RequisicoesView,
    DicasView,
    EmprestimosView,
    RelatoriosView,
    AuditoriaView,
    UsersListView,
    move_ticket,
    ticket_detail,
    ticket_reclassify,
    ticket_message,
    ticket_update,
    ticket_delete,
    email_templates_update,
    whatsapp_group_lookup,
    whatsapp_templates_update,
    whatsapp_settings_update,
    ticket_reopen,
    ticket_timer_action,
    ws_tickets_ping,
    app_version_api,
    chamados_new_alert_api,
    inventory_push_api,
    chamados_fill_spreadsheet,
    pendencias_toggle_status_api,
    pendencias_create_api,
    pendencias_create_ticket_api,
    chamados_close_category_create_api,
)

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('usuarios/', UsersListView.as_view(), name='usuarios'),
    path('atribuicoes/', AtribuicoesView.as_view(), name='atribuicoes'),
    path('atribuicoes/relatorio/', AtribuicoesReportView.as_view(), name='atribuicoes_relatorio'),
    path('pendencias/', PendenciasView.as_view(), name='pendencias'),
    path('acessos/', AcessosView.as_view(), name='acessos'),
    path('equipamentos/', EquipamentosView.as_view(), name='equipamentos'),
    path('softwares/', SoftwaresView.as_view(), name='softwares'),
    path('insumos/', InsumosView.as_view(), name='insumos'),
    path('protocolos/', ProtocolosView.as_view(), name='protocolos'),
    path('requisicoes/', RequisicoesView.as_view(), name='requisicoes'),
    path('dicas/', DicasView.as_view(), name='dicas'),
    path('emprestimos/', EmprestimosView.as_view(), name='emprestimos'),
    path('relatorios/', RelatoriosView.as_view(), name='relatorios'),
    path('auditoria/', AuditoriaView.as_view(), name='auditoria'),
    path('chamados/', ChamadosView.as_view(), name='chamados'),
    path('chamados/mover/', move_ticket, name='chamados_mover'),
    path('chamados/detalhe/<int:ticket_id>/', ticket_detail, name='chamados_detalhe'),
    path('chamados/reclassificar/', ticket_reclassify, name='chamados_reclassificar'),
    path('chamados/mensagem/', ticket_message, name='chamados_mensagem'),
    path('chamados/atualizar/', ticket_update, name='chamados_atualizar'),
    path('chamados/excluir/', ticket_delete, name='chamados_excluir'),
    path('chamados/email-templates/', email_templates_update, name='chamados_email_templates'),
    path('chamados/whatsapp-templates/', whatsapp_templates_update, name='chamados_whatsapp_templates'),
    path('chamados/whatsapp-group-lookup/', whatsapp_group_lookup, name='chamados_whatsapp_group_lookup'),
    path('chamados/whatsapp-settings/', whatsapp_settings_update, name='chamados_whatsapp_settings'),
    path('chamados/reabrir/', ticket_reopen, name='chamados_reabrir'),
    path('chamados/timer/', ticket_timer_action, name='chamados_timer'),
    path('chamados/preencher-planilha/', chamados_fill_spreadsheet, name='chamados_preencher_planilha'),
    path('ws/tickets/', ws_tickets_ping, name='ws_tickets_ping'),
    path('api/app/version/', app_version_api, name='app_version_api'),
    path('api/chamados/novos/', chamados_new_alert_api, name='chamados_new_alert_api'),
    path('api/chamados/close-categories/create/', chamados_close_category_create_api, name='chamados_close_category_create_api'),
    path('api/inventory/push/', inventory_push_api, name='inventory_push_api'),
    path('api/pendencias/toggle-status/', pendencias_toggle_status_api, name='pendencias_toggle_status_api'),
    path('api/pendencias/create/', pendencias_create_api, name='pendencias_create_api'),
    path('api/pendencias/create-ticket/', pendencias_create_ticket_api, name='pendencias_create_ticket_api'),
    path('', DashboardView.as_view(), name='dashboard'),
]
