"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    for line in ENV_PATH.read_text(encoding='utf-8-sig').splitlines():
        raw = line.strip()
        if not raw or raw.startswith('#') or '=' not in raw:
            continue
        key, value = raw.split('=', 1)
        key = key.strip().lstrip('\ufeff')
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ[key] = value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0_@z3ayq+ia$467tp90s#4bxdg5zhd@e&4vaf(glre_t@#f=nq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', socket.gethostname()]
extra_hosts = os.environ.get('EXTRA_ALLOWED_HOSTS', '')
if extra_hosts:
    for host in extra_hosts.split(','):
        normalized = host.strip()
        if normalized and normalized not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(normalized)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_path_raw = (os.environ.get('ERP_DB_PATH', '') or '').strip()
if _db_path_raw:
    _db_path = Path(_db_path_raw)
    if _db_path.suffix:
        _db_name = _db_path
    else:
        _db_name = _db_path / 'db.sqlite3'
else:
    _db_name = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chamados'
LOGOUT_REDIRECT_URL = 'login'

# LDAP / Active Directory (SIDERTEC) - via ldap3
AUTHENTICATION_BACKENDS = [
    'core.auth_backend.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AD_LDAP_SERVER_URI = 'ldap://192.168.22.8:389'
AD_LDAP_BASE_DN = 'dc=sidertec,dc=intra,dc=net'
AD_LDAP_BIND_DN = 'glpi_ldap@sidertec.intra.net'
AD_LDAP_BIND_PASSWORD = os.environ.get('ERP_LDAP_BIND_PASSWORD', '')
AD_LDAP_USER_FILTER = '(&(objectCategory=person)(objectclass=user)(sAMAccountName=%(user)s))'

AD_LDAP_USER_ATTR_MAP = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}

AD_LDAP_IMPORT_FILTER = '(&(objectCategory=person)(objectclass=user))'
AD_LDAP_IMPORT_ATTR_MAP = {
    'username': 'sAMAccountName',
    'full_name': 'displayName',
    'department': 'department',
    'phone': 'telephoneNumber',
    'mobile': 'mobile',
    'email': 'mail',
    'guid': 'objectGUID',
    'active': 'userAccountControl',
}

# Email
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Chamados Sidertec <no-reply@sidertec>')
EMAIL_NOTIFY_NEW_TICKET_USERNAMES = [
    item.strip().lower()
    for item in os.environ.get('EMAIL_NOTIFY_NEW_TICKET_USERNAMES', 'fabiano.polone').split(',')
    if item.strip()
]

# WhatsApp (WAPI)
WAPI_DEFAULT_GROUP_JID = os.environ.get('WAPI_DEFAULT_GROUP_JID', '')

# Acessos
ACCESS_ROOT_PATH = os.environ.get('ACCESS_ROOT_PATH', r'\\SRV-FS\\Sidertec')

# Exportacao de chamados para planilha mensal
CHAMADOS_XLSX_PATH = os.environ.get(
    'CHAMADOS_XLSX_PATH',
    r'S:\TI\Documentos\Chamados\Chamados 2026 - Fabiano.xlsx',
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
